### ISSUE TITLE
Discuss desktop app project structure

### ISSUE THREAD

**Issue by Pekmen** [coremind-oss/ttasm-desktop-app#4]
The current folder structure of desktop app will quickly become inadequate as our app will start expanding. I am suggesting a common Python project structure, so we can break everything into modules and expand it as we go.

Here is an example of my suggestion:
```
ttasm-desktop-app/
├── main.py
└── ttasm-desktop
    ├── __init__.py
    ├── app.py
    ├── ui
    │   ├── __init__.py
    │   ├── tray.py
    │   └── login.py
    ├── network
    │   ├── __init__.py
    │   └── login_handler.py
    └── some package
        └── __init__.py

etc...

```
If we decide to use Qt Designer later, we can modify ui folder to hold only .ui files exported by Designer

**Comment by LukaDjordjevic** [comment]
Also discuss and create detailed flowcharts describing exact app behavior.
