### ISSUE TITLE
Investigate how to manipulate multiple screens

### ISSUE THREAD

**Issue by daliborduric** [coremind-oss/ttasm-desktop-app#5]
If there are more then a single screen, it messes up the login form.
Try to position it in the middle of the primary screen every time, everywhere...

**Comment by Pekmen** [comment]
Can someone with dual monitors test if this works?

https://github.com/coremind-oss/ttasm-desktop-app/tree/Issue-5-Pekmen

**Comment by daliborduric** [comment]
@Pekmen it worked for me, good job

**Comment by daliborduric** [comment]
@Pekmen Set yourself as assignee if you are working on this. Also move it into the In Progress column so that others can see if you're working on this.

I did it for you this time ;)

**Comment by Pekmen** [comment]
Sorry, it seems that I am still in a mindset of a lone wolf programmer :D

**Comment by LukaDjordjevic** [comment]
Did a similar thing on https://github.com/coremind-oss/ttasm-desktop-app/tree/Issue-5-Luka
Don't have multiple monitors to test it though (but i think it should work).

**Comment by daliborduric** [comment]
You'll have multiple monitors when office is set up ;)

**Comment by LukaDjordjevic** [comment]
Haha I want at least three :)

also I tested Pekmen's window flags but maximize button still shows up somehow.  CustomizeWindowHint is supposed to remove all the default buttons. Will try to look into it.

**Comment by daliborduric** [comment]
It might be an OS thing. are you using Ubuntu?

**Comment by Pekmen** [comment]
Can you post a screenshot? It looks like this on my machine:

![screenshot_2017-05-30_13-59-10](https://cloud.githubusercontent.com/assets/9119728/26582148/49eab52a-4540-11e7-9f94-9ea05ec83fe6.png)

**Comment by LukaDjordjevic** [comment]
yes, ubuntu 16.04 with default window manager (gnome i think)

**Comment by LukaDjordjevic** [comment]
![login popup](https://cloud.githubusercontent.com/assets/28875936/26582226/a0bcbe16-4540-11e7-82c9-46b49f0b9bb6.png)

There it is in the upper left corner. If i click it it works (maximizes window). I think I see it on your screenshot also.

**Comment by Pekmen** [comment]
let's continue discussion on Issue #6 board

**Comment by LukaDjordjevic** [comment]
Sure. I think i solved it, will post solution there.
