### ISSUE TITLE
Disable minimise, maximise and close buttons in the default window

### ISSUE THREAD

**Issue by daliborduric** [coremind-oss/ttasm-desktop-app#6]
explore options and try to implement

**Comment by LukaDjordjevic** [comment]
There is a Qt.FramelessWindowHint flag for borderless windows. Appropriate line in Pekman code should read
`self.setWindowFlags(QtCore.Qt.FramelessWindowHint | QtCore.Qt.WindowStaysOnTopHint)`

**Comment by Pekmen** [comment]
Luka, that would just remove title bar entirely and render window immovable , like a Popup flag did.

**Comment by Pekmen** [comment]
Alright, this was a bit more work then I hoped. 
Flags ending with Hint are just that - hints. These flags are not explicit and can be ignored by window managers on different platforms, especially if we place them in such order that window manager doesn't like.

So after some time I found the combination that works in Xfce environment, but I can't guarantee it will work 100% cross-platform:


```python
self.setWindowFlags(  QtCore.Qt.WindowStaysOnTopHint | 
                      QtCore.Qt.CustomizeWindowHint |
                      QtCore.Qt.WindowTitleHint)
```

**Comment by daliborduric** [comment]
just push the code when you got something, create a pull request and we will investigate what works and what doesn't

**Comment by Pekmen** [comment]
So Luka, the thing in the left corner on [my screenshot](https://cloud.githubusercontent.com/assets/9119728/26582148/49eab52a-4540-11e7-9f94-9ea05ec83fe6.png) is dropdown menu, not maximize button. It shouldn't even be able to maximize because I set the fixed size of the window. Can you resize the window with your mouse?

**Comment by LukaDjordjevic** [comment]
Doing setFixedSize removes maximize button (I get that now). I guess i tested your flags without setFixedSize line, so that's why maximize was still there. It works fine now, my bad.
